<div id="delivery-date-shipping">
    <strong><?php echo __('Delivery Date') ?></strong>
    <span class="price"><?=$block->getDeliveryDate(); ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#delivery-date-shipping').detach();
            $('.order-shipping-address').eq(1).append(element);
        }
    );
</script>